### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by puckey** [rosszurowski/async-json-parse#1]
http://azimi.me/2015/07/30/non-blocking-async-json-parse.html

**Comment by rosszurowski** [comment]
Oh wow, good to know. I'll add a note to the README until there's an actual asynchronous solution that comes along (or I find a way to make this module work with WebWorkers).

**Comment by rosszurowski** [comment]
Closed (I guess?) with https://github.com/rosszurowski/async-json-parse/commit/5dce3589733a204b78353704443da757a722d609
